import { StyleSheet } from 'react-native';
export const homeStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#FFFAF2' },
  scrollContent: {
    paddingHorizontal: 21,
    paddingTop: 12,
    paddingBottom: 24,
    width: '100%',
    maxWidth: 520,
    alignSelf: 'center',
  },
  topbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 17,
  },
  wordmark: { width: 95, height: 32, resizeMode: 'contain' },
  agePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 11,
    backgroundColor: '#F4E8DC',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FFF8F0',
    elevation: 2,
    shadowColor: '#B79A80',
    shadowOffset: { width: 2, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
  },
  agePillText: { fontSize: 11, fontWeight: '700', color: '#8C756C' },
  greeting: { flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 18 },
  avatar: {
    width: 43,
    height: 43,
    padding: 2,
    borderRadius: 16,
    backgroundColor: '#F0E2D3',
    borderWidth: 1,
    borderColor: '#FFF7EB',
  },
  avatarImage: { width: '100%', height: '100%', resizeMode: 'contain' },
  greetingTitle: { fontSize: 20, fontWeight: '800', color: '#393044', letterSpacing: -0.65 },
  greetingSub: { fontSize: 11, color: '#9C8E9E', marginTop: 3 },
  hero: {
    minHeight: 195,
    padding: 18,
    borderRadius: 25,
    backgroundColor: '#F2DFC9',
    borderWidth: 1.5,
    borderTopColor: '#FFF4E5',
    borderLeftColor: '#FFF4E5',
    borderRightColor: '#E9CDB4',
    borderBottomColor: '#E7CBB2',
    shadowColor: '#A47C55',
    shadowOffset: { width: 4, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  heroScene: { position: 'absolute', right: 6, bottom: 12 },
  sceneToggle: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#FFF5E3',
    backgroundColor: '#FFF2DE99',
  },
  heroKicker: {
    fontSize: 8,
    letterSpacing: 1.1,
    fontWeight: '800',
    color: '#AE8768',
    marginBottom: 7,
  },
  heroTitle: {
    fontSize: 22,
    lineHeight: 25,
    letterSpacing: -0.8,
    fontWeight: '800',
    color: '#393044',
    maxWidth: '45%',
    marginTop: 10,
    marginBottom: 20,
  },
  primary: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 7,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    paddingHorizontal: 12,
    minHeight: 38,
    backgroundColor: '#956BBC',
    borderRadius: 13,
    borderWidth: 1.5,
    borderTopColor: '#CBA8E3',
    borderLeftColor: '#CBA8E3',
    borderRightColor: '#8C60B5',
    borderBottomColor: '#8054A9',
    shadowColor: '#946EAE',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 3,
  },
  primaryText: { fontSize: 11, fontWeight: '700', color: '#FFFFFF' },
  star: { position: 'absolute', top: 11, right: 12, color: '#DDB655', fontSize: 17 },
  sectionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    marginTop: 24,
    marginBottom: 13,
  },
  sectionTitle: { fontSize: 15, fontWeight: '800', letterSpacing: -0.4, color: '#393044', flex: 1 },
  smallLink: { fontSize: 11, fontWeight: '700', color: '#9975BA' },
  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  category: {
    width: '47.5%',
    flexGrow: 1,
    minHeight: 106,
    padding: 13,
    borderRadius: 21,
    borderWidth: 1.5,
    borderColor: '#FFFFFFA0',
    shadowColor: '#9F8675',
    shadowOffset: { width: 3, height: 4 },
    shadowOpacity: 0.11,
    shadowRadius: 5,
    elevation: 2,
  },
  categoryTitle: { fontSize: 14, fontWeight: '800', color: '#393044' },
  categoryHint: { fontSize: 10, lineHeight: 14, marginTop: 5, maxWidth: 70 },
  categoryArt: {
    position: 'absolute',
    width: '49%',
    height: 82,
    right: 0,
    bottom: 0,
    resizeMode: 'contain',
  },
  continueCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderRadius: 22,
    backgroundColor: '#F1DFCC',
    borderWidth: 1.5,
    borderTopColor: '#FFF4E4',
    borderLeftColor: '#FFF4E4',
    borderRightColor: '#E9D1B9',
    borderBottomColor: '#E5CEB6',
    shadowColor: '#A78461',
    shadowOffset: { width: 3, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 2,
  },
  continueArt: {
    width: 61,
    height: 61,
    borderRadius: 16,
    backgroundColor: '#FCF6ED',
    borderWidth: 1,
    borderColor: '#FFFEF9',
  },
  continueCopy: { flex: 1, minWidth: 0 },
  eyebrow: { fontSize: 8, letterSpacing: 0.8, fontWeight: '700', color: '#9C869C' },
  continueTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#393044',
    marginTop: 5,
    marginBottom: 9,
  },
  progressRow: { flexDirection: 'row', gap: 7, alignItems: 'center' },
  track: { height: 5, borderRadius: 5, backgroundColor: '#DECCBC', flex: 1, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 5, backgroundColor: '#AA85CC' },
  progressText: { fontSize: 9, color: '#957D87' },
  playOrb: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#AA85CE',
    borderRadius: 13,
    borderTopWidth: 1.5,
    borderTopColor: '#DDC8EB',
    borderBottomWidth: 3,
    borderBottomColor: '#946BBD',
  },
  recommendations: { gap: 12, paddingBottom: 9 },
  activity: {
    position: 'relative',
    padding: 11,
    borderRadius: 21,
    backgroundColor: '#F7EFE5',
    borderWidth: 1,
    borderColor: '#FFF8F0',
    shadowColor: '#9D816A',
    shadowOffset: { width: 2, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  compactCard: { width: 164 },
  gridCard: { width: '48%' },
  activityGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 13,
  },
  thumb: {
    height: 92,
    borderRadius: 15,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  thumbImage: { width: 112, height: 88, resizeMode: 'contain' },
  saveButton: {
    position: 'absolute',
    top: 15,
    right: 15,
    width: 32,
    height: 32,
    borderRadius: 11,
    backgroundColor: '#FFFCF3',
    borderWidth: 1,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  savedButton: { backgroundColor: '#EBDCF6' },
  activityTitle: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '800',
    color: '#393044',
    marginTop: 6,
    marginBottom: 6,
  },
  meta: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  metaText: { fontSize: 9, color: '#94869C' },
  bottomNote: {
    textAlign: 'center',
    fontSize: 10,
    lineHeight: 18,
    color: '#A08DA3',
    marginTop: 23,
  },
  pageTitle: { fontSize: 25, fontWeight: '800', letterSpacing: -0.8, color: '#393044' },
  pageSub: { fontSize: 12, color: '#99899F', lineHeight: 19, marginTop: 5, marginBottom: 20 },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 16,
    backgroundColor: '#F3E7DC',
    borderWidth: 1,
    borderColor: '#FFF8EC',
    paddingHorizontal: 12,
    marginBottom: 13,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 44,
    paddingVertical: 11,
    fontSize: 13,
    color: '#6D567C',
  },
  filters: { gap: 7, paddingBottom: 18 },
  filter: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EADFda',
    backgroundColor: '#FAF1E7',
  },
  filterText: { fontSize: 11, fontWeight: '700', color: '#9B879D' },
  activeFilter: { backgroundColor: '#E8D9F4', borderColor: '#DECAEF' },
  empty: { padding: 25, alignItems: 'center' },
  emptyArt: { width: 150, height: 130, resizeMode: 'contain' },
  emptyTitle: {
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '700',
    color: '#655371',
    marginTop: 7,
  },
  emptyText: {
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 20,
    color: '#9A879E',
    marginVertical: 18,
  },
  nav: {
    flexDirection: 'row',
    paddingTop: 10,
    paddingHorizontal: 12,
    backgroundColor: '#FFFCF7',
    borderTopWidth: 1,
    borderTopColor: '#F0E4D9',
  },
  navItem: { flex: 1, alignItems: 'center', gap: 5, minHeight: 48 },
  navSymbol: {
    width: 47,
    height: 30,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navActive: { backgroundColor: '#EDE1F6', borderTopWidth: 1, borderTopColor: '#FDF5FF' },
  navLabel: { fontSize: 10, fontWeight: '600', color: '#A394AA' },
  overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: '#38274466', padding: 12 },
  ageSheet: { padding: 23, paddingBottom: 30, borderRadius: 30, backgroundColor: '#FFFAF2' },
  sheetTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  closeButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EFE4F5',
    borderRadius: 12,
  },
  ageGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  ageOption: {
    width: '47.5%',
    flexGrow: 1,
    alignItems: 'center',
    padding: 20,
    borderRadius: 19,
    borderWidth: 2,
    borderColor: '#FFF3E5',
    backgroundColor: '#F3E5D7',
  },
  ageSelected: { borderColor: '#B897D0', backgroundColor: '#E9DAF4' },
  ageNumber: { fontSize: 24, fontWeight: '800', color: '#9064B5' },
  ageYears: { fontSize: 11, color: '#957A93', marginTop: 3 },
  ageFine: { fontSize: 10, color: '#AD9BB2', textAlign: 'center', marginTop: 18 },
});

export const tabletStyles = StyleSheet.create({
  topbar: { marginBottom: 24 },
  wordmark: { width: 120, height: 40 },
  agePill: { minHeight: 44, paddingHorizontal: 15, borderRadius: 16 },
  agePillText: { fontSize: 13 },
  greeting: { gap: 14, marginBottom: 24 },
  avatar: { width: 54, height: 54, borderRadius: 19 },
  greetingTitle: { fontSize: 27 },
  greetingSub: { fontSize: 13, marginTop: 5 },
  hero: { padding: 26, borderRadius: 30 },
  heroKicker: { fontSize: 10, letterSpacing: 1.5, maxWidth: '43%' },
  heroTitle: {
    fontSize: 32,
    lineHeight: 37,
    maxWidth: '43%',
    marginTop: 13,
    marginBottom: 24,
    letterSpacing: -1,
  },
  primary: { minHeight: 48, paddingVertical: 13, paddingHorizontal: 18, borderRadius: 16, gap: 10 },
  primaryText: { fontSize: 13 },
  sceneToggle: { width: 44, height: 44, top: 10, right: 10, borderRadius: 15 },
  sectionRow: { marginTop: 30, marginBottom: 16 },
  sectionTitle: { fontSize: 20 },
  smallLink: { fontSize: 13, paddingVertical: 12 },
  category: { minHeight: 180, padding: 18, paddingBottom: 112, borderRadius: 25 },
  categoryTitle: { fontSize: 17 },
  categoryHint: { fontSize: 11, lineHeight: 17, maxWidth: '100%', marginTop: 8 },
  categoryArt: { width: 110, height: 100, right: 3, bottom: 4 },
  continueCard: { padding: 18, gap: 18, borderRadius: 26 },
  continueArt: { width: 82, height: 82, borderRadius: 20 },
  continueTitle: { fontSize: 18, marginTop: 8, marginBottom: 13 },
  eyebrow: { fontSize: 10 },
  progressText: { fontSize: 11 },
  track: { height: 7 },
  playOrb: { width: 48, height: 48, borderRadius: 16 },
  activity: { padding: 14, borderRadius: 25 },
  thumb: { height: 134, borderRadius: 19 },
  thumbImage: { width: 150, height: 126 },
  saveButton: { width: 44, height: 44, borderRadius: 14, top: 19, right: 19 },
  activityTitle: { fontSize: 16, lineHeight: 22 },
  metaText: { fontSize: 11 },
  bottomNote: { fontSize: 11, lineHeight: 20, marginTop: 28 },
  pageTitle: { fontSize: 32 },
  pageSub: { fontSize: 14, lineHeight: 23 },
  search: { minHeight: 52, paddingHorizontal: 16 },
  searchInput: { fontSize: 16, minHeight: 50 },
  filter: { minHeight: 44, paddingHorizontal: 17 },
  filterText: { fontSize: 13 },
  nav: { paddingTop: 13 },
  navItem: { minHeight: 60, gap: 6 },
  navSymbol: { width: 60, height: 37, borderRadius: 15 },
  navLabel: { fontSize: 12 },
  closeButton: { width: 44, height: 44 },
});
