import { StyleSheet } from 'react-native';
export const authStyles = StyleSheet.create({
  fill: {
    flex: 1,
    backgroundColor: '#FFFAF2',
  },
  disabled: {
    opacity: 0.5,
  },
  icon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  authNav: {
    height: 56,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  back: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: '#F4EADD',
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 23,
    paddingBottom: 26,
  },
  column: {
    width: '100%',
    maxWidth: 410,
  },
  brand: {
    width: 190,
    height: 127,
    alignSelf: 'center',
    marginTop: 6,
    marginBottom: 5,
  },
  brandCompact: {
    width: 130,
    height: 87,
    marginTop: 0,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: -0.8,
    color: '#40344C',
    marginTop: 8,
    marginBottom: 7,
  },
  titleCompact: {
    fontSize: 25,
  },
  subtitle: {
    fontSize: 12,
    lineHeight: 19,
    textAlign: 'center',
    color: '#948496',
    marginBottom: 21,
    paddingHorizontal: 8,
  },
  card: {
    backgroundColor: '#F3E2D0',
    borderRadius: 27,
    padding: 21,
    borderWidth: 1.5,
    borderTopColor: '#FFF5E8',
    borderLeftColor: '#FFF4E6',
    borderRightColor: '#E6CDB5',
    borderBottomColor: '#DEC3AA',
    shadowColor: '#A68666',
    shadowOpacity: 0.17,
    shadowOffset: {
      width: 4,
      height: 7,
    },
    shadowRadius: 12,
    elevation: 4,
  },
  loginHeader: {
    position: 'relative',
    alignItems: 'center',
    marginBottom: 4,
  },
  loginCard: {
    padding: 20,
    borderRadius: 29,
    backgroundColor: '#F4E4D5',
    borderTopColor: '#FFF8EF',
    borderLeftColor: '#FFF5E9',
    borderRightColor: '#E7D2BE',
    borderBottomColor: '#DEC3AA',
  },
  fieldGroup: {
    marginBottom: 17,
  },
  label: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6F5E78',
    marginLeft: 3,
    marginBottom: 8,
  },
  field: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 53,
    paddingLeft: 13,
    borderRadius: 16,
    backgroundColor: '#FFFBF5',
    borderWidth: 1.5,
    borderTopColor: '#FFFFFF',
    borderLeftColor: '#FFFFFF',
    borderRightColor: '#EEE1D3',
    borderBottomColor: '#E6D8C8',
    shadowColor: '#9F8567',
    shadowOffset: {
      width: 2,
      height: 3,
    },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
  },
  focused: {
    borderColor: '#B194CA',
  },
  fieldInvalid: {
    borderColor: '#C67C71',
  },
  country: {
    fontSize: 12,
    color: '#7F6C8B',
    marginLeft: 9,
    marginRight: 10,
    paddingRight: 10,
    borderRightWidth: 1,
    borderRightColor: '#E7DCE9',
  },
  input: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 13,
    minHeight: 51,
    fontSize: 14,
    color: '#493C55',
  },
  codeInput: {
    fontSize: 26,
    letterSpacing: 8,
    textAlign: 'center',
    fontWeight: '600',
    paddingLeft: 0,
  },
  eye: {
    width: 44,
    minHeight: 49,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorText: {
    fontSize: 11,
    lineHeight: 16,
    color: '#9B534C',
    marginTop: 6,
    marginLeft: 3,
    marginBottom: 4,
  },
  hint: {
    fontSize: 10,
    lineHeight: 16,
    color: '#9C889F',
    marginTop: 8,
    marginHorizontal: 3,
  },
  linkTap: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  link: {
    fontSize: 11,
    fontWeight: '600',
    color: '#8960AA',
  },
  forgot: {
    alignItems: 'flex-end',
    marginTop: -11,
    marginBottom: 7,
  },
  buttonBase: {
    borderRadius: 18,
    backgroundColor: '#7F53A7',
    paddingBottom: 4,
    marginTop: 4,
    marginBottom: 7,
    shadowColor: '#9974AF',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  button: {
    minHeight: 53,
    borderRadius: 17,
    paddingVertical: 12,
    paddingHorizontal: 13,
    backgroundColor: '#9A70BF',
    borderWidth: 1.5,
    borderTopColor: '#DCC3EE',
    borderLeftColor: '#C5A5DF',
    borderRightColor: '#9D75C2',
    borderBottomColor: '#8D61B8',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 13,
  },
  buttonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  arrowBubble: {
    width: 25,
    height: 25,
    borderRadius: 9,
    backgroundColor: '#BE98D8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  signup: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 5,
    marginTop: 8,
    marginBottom: -5,
  },
  muted: {
    fontSize: 11,
    color: '#9A849D',
  },
  guardian: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginTop: -1,
    marginBottom: 14,
    minHeight: 40,
  },
  guardianText: {
    fontSize: 11,
    color: '#846D8E',
    flex: 1,
    lineHeight: 17,
  },
  checkbox: {
    width: 21,
    height: 21,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#B19AC1',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFBF5',
  },
  checked: {
    backgroundColor: '#9974BB',
  },
  errorBanner: {
    backgroundColor: '#F8E5E0',
    color: '#985D57',
    borderRadius: 12,
    padding: 11,
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 15,
  },
  infoBanner: {
    backgroundColor: '#F1E8F8',
    color: '#87629E',
    borderRadius: 12,
    padding: 11,
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 15,
  },
  symbol: {
    width: 68,
    height: 68,
    borderRadius: 24,
    backgroundColor: '#EBDFF5',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 9,
    marginBottom: 22,
    borderWidth: 1,
    borderColor: '#F5EAFE',
  },
  verifyBanner: {
    backgroundColor: '#F6EFFB',
    padding: 12,
    borderWidth: 1,
    borderColor: '#DDCEE9',
    borderRadius: 13,
    alignItems: 'center',
    marginBottom: 18,
  },
  verifyNote: {
    fontSize: 9,
    lineHeight: 17,
    textAlign: 'center',
    color: '#9174A5',
  },
  demoCode: {
    fontSize: 18,
    letterSpacing: 3,
    fontWeight: '600',
    color: '#8055A1',
    marginVertical: 3,
  },
  codeActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    gap: 7,
  },
  successCopy: {
    fontSize: 13,
    lineHeight: 24,
    textAlign: 'center',
    color: '#8E7B98',
    marginBottom: 22,
  },
});
